### ISSUE TITLE
Request: extract gpio i2c or RTC integrate

### ISSUE THREAD

**Issue by gablau** [openenergymonitor/Hardware#1]
it's possible to extract the bus i2c (pin 4 and 6) from gpio of the raspberry pi? 
are useful for connecting a RTC or a display.
or maybe integrate an RTC with a small battery type CR1220 ??
Great job!!

**Comment by glynhudson** [comment]
Hi Gablau, 
Thanks for your kind words. What unit are you referring to?

**Comment by gablau** [comment]
Sorry, I was referring to the RFM69Pi V3 unit!!!
The best thing would be to integrate the DS3231, but that's fine too but the DS1307 that requires a quartz to run and is less precise.

**Comment by glynhudson** [comment]
Ah gotcha. The io which is broken out on the RFM69Pi is from the ATmega328.
The RFM69Pi only uses serial UART and one gpio pin from the Pi for rest.
All the other Pi gpio pins are available for use as normal

- sent from my mobile device
