### ISSUE TITLE
Components value

### ISSUE THREAD

**Issue by pilotak** [openenergymonitor/Hardware#2]
Could you please tell me what are the values of following components, it's missing in eagle drawing:
* L1
* D2, D3, D4, D5, D6

**Comment by pilotak** [comment]
Sorry, forgot to say it's regarding emonTx_V3.4

**Comment by glynhudson** [comment]
See the emontx V3.4 BOM: https://github.com/openenergymonitor/Hardware/blob/master/emonTxV3/emonTx_V3.4/emonTx_V3.4_BOM.ods (its in open office formatt)
