### ISSUE TITLE
break out the Arduino A6 & A7

### ISSUE THREAD

**Issue by mkeyno** [openenergymonitor/Hardware#5]
hi , first of all apologized to draw issue for my question , however I was wondering why didn't you break out the A6 & A7 pin for extra V or I measurements, I thought with reserve the A4 &  A5 for I2c ,still have 6 Analogue pin for measuring 3*2 V-I  line
actually base on your hardware design I made[ pre design schematic](https://github.com/mkeyno/Smart_plantation) using ESP as  communication control center with one Arduino connected as I2c slave, I really appreciated if I have your comments or idea about that
BR

**Comment by glynhudson** [comment]
Which hardware design are you referring to?

**Comment by mkeyno** [comment]
I've check  schematic of emonTxV2 to V3.5 , none of them break out the A6 & A7 Arduino pin

**Comment by glynhudson** [comment]
On the emonTx V3 A6 is broken out on the RJ45 terminal for general use and A7 is used to read the DC battery voltage. See port map

https://wiki.openenergymonitor.org/index.php/EmonTx_V3.4#emonTx_V3.4_2
